import type { Run, Result } from "../types/index.js";
import { getScenario } from "../db/scenarios.js";

export function generateGitHubActionsWorkflow(): string {
  return `name: AI QA Tests
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install -g @hasna/testers
      - run: testers install-browser
      - run: testers run \${{ env.TEST_URL }} --json --output results.json --github-comment
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          TEST_URL: \${{ vars.TEST_URL || 'http://localhost:3000' }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
      - run: testers report --latest --output report.html
        if: always()
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: |
            report.html
            results.json
`;
}

/**
 * Build a Markdown PR comment from a run + its results.
 *
 * Exported for testing. The format is:
 *   - Headline with pass/fail icon, counts, pass-rate, URL
 *   - Table of scenario results (capped at 20 rows)
 *   - Optional link to a dashboard
 *   - Footer attribution
 */
export function formatPRComment(run: Run, results: Result[], dashboardUrl?: string): string {
  const icon = run.status === "passed" ? "✅" : run.status === "failed" ? "❌" : "⚠️";
  const passRate = run.total > 0 ? Math.round((run.passed / run.total) * 100) : 0;

  // Put failures first so reviewers see them immediately.
  const ordered = [...results].sort((a, b) => {
    const rank = (s: string) => (s === "failed" ? 0 : s === "error" ? 1 : s === "flaky" ? 2 : s === "skipped" ? 3 : 4);
    return rank(a.status) - rank(b.status);
  });

  const MAX_ROWS = 20;
  const rows = ordered.slice(0, MAX_ROWS).map((r) => {
    const rowIcon = r.status === "passed" ? "✅"
      : r.status === "failed" ? "❌"
      : r.status === "error" ? "⚠️"
      : r.status === "flaky" ? "🟡"
      : "⏭️";
    const dur = r.durationMs > 0 ? `${(r.durationMs / 1000).toFixed(1)}s` : "—";
    const scenario = (() => {
      try { return getScenario(r.scenarioId); } catch { return null; }
    })();
    const name = scenario ? scenario.name : r.scenarioId.slice(0, 8);
    // Escape pipe chars so markdown tables don't break on scenario names containing "|".
    const safeName = name.replace(/\|/g, "\\|");
    const errSource = r.error ?? r.reasoning ?? "";
    const err = errSource
      ? ` ${errSource.replace(/\s+/g, " ").slice(0, 140).replace(/\|/g, "\\|")}`
      : "";
    return `| ${rowIcon} | ${safeName} | ${r.status} | ${dur} |${err} |`;
  }).join("\n");

  const truncated = results.length > MAX_ROWS ? `\n_...and ${results.length - MAX_ROWS} more_` : "";
  const dashLink = dashboardUrl ? `\n\n[View full report →](${dashboardUrl}/runs/${run.id})` : "";

  const totalCostCents = results.reduce((sum, r) => sum + (r.costCents ?? 0), 0);
  const costStr = totalCostCents > 0 ? ` · $${(totalCostCents / 100).toFixed(4)}` : "";

  const headerRow = "| | Scenario | Status | Duration | Details |\n|---|---|---|---|---|";
  const body = results.length > 0
    ? `${headerRow}\n${rows}${truncated}`
    : `_No scenarios ran. Use \`testers add\` to create scenarios or run with a URL to auto-generate them._`;

  return `## ${icon} AI QA Tests — ${run.status.toUpperCase()}

**${run.passed}/${run.total} passed** (${passRate}%) · URL: \`${run.url}\`${costStr}

${body}${dashLink}

_Generated by [@hasna/testers](https://www.npmjs.com/package/@hasna/testers)_`;
}

/** Resolve the PR number from options or GitHub Actions env vars. Returns `null` if not resolvable. */
export function resolvePullRequestNumber(explicit?: number): number | null {
  if (explicit && Number.isFinite(explicit)) return explicit;

  const fromEnv = process.env["GITHUB_PR_NUMBER"];
  if (fromEnv) {
    const parsed = parseInt(fromEnv, 10);
    if (Number.isFinite(parsed)) return parsed;
  }

  // GITHUB_REF format for pull requests: refs/pull/123/merge
  const ref = process.env["GITHUB_REF"] ?? "";
  const match = ref.match(/refs\/pull\/(\d+)\//);
  if (match && match[1]) {
    const parsed = parseInt(match[1], 10);
    if (Number.isFinite(parsed)) return parsed;
  }

  return null;
}

export async function postGitHubComment(
  run: Run,
  results: Result[],
  options?: { prNumber?: number; dashboardUrl?: string },
): Promise<boolean> {
  const token = process.env["GITHUB_TOKEN"];
  if (!token) return false;

  const prNumber = resolvePullRequestNumber(options?.prNumber);
  if (prNumber === null) return false;

  // Detect repo from GITHUB_REPOSITORY (owner/repo)
  const repo = process.env["GITHUB_REPOSITORY"];
  if (!repo) return false;

  const body = formatPRComment(run, results, options?.dashboardUrl ?? process.env["TESTERS_DASHBOARD_URL"]);
  const apiUrl = `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`;

  try {
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({ body }),
    });
    return response.ok;
  } catch {
    return false;
  }
}
