import type { Run, Result } from "../types/index.js";

export function generateGitHubActionsWorkflow(): string {
  return `name: AI QA Tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install -g @hasna/testers
      - run: testers install-browser
      - run: testers run \${{ env.TEST_URL }} --json --output results.json --github-comment
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          TEST_URL: \${{ vars.TEST_URL || 'http://localhost:3000' }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
      - run: testers report --latest --output report.html
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: |
            report.html
            results.json
`;
}

function formatPRComment(run: Run, results: Result[], dashboardUrl?: string): string {
  const icon = run.status === "passed" ? "✅" : "❌";
  const passRate = run.total > 0 ? Math.round((run.passed / run.total) * 100) : 0;

  const rows = results
    .slice(0, 20) // cap at 20 rows to avoid huge comments
    .map((r) => {
      const s = r.status === "passed" ? "✅" : r.status === "failed" ? "❌" : "⚠️";
      const dur = r.durationMs > 0 ? `${(r.durationMs / 1000).toFixed(1)}s` : "—";
      const err = r.error ? ` — ${r.error.slice(0, 80)}` : "";
      return `| ${s} | ${r.status} | ${dur} |${err}`;
    })
    .join("\n");

  const truncated = results.length > 20 ? `\n_...and ${results.length - 20} more_` : "";
  const dashLink = dashboardUrl ? `\n\n[View full report →](${dashboardUrl}/runs/${run.id})` : "";

  return `## ${icon} AI QA Tests — ${run.status.toUpperCase()}

**${run.passed}/${run.total} passed** (${passRate}%) · URL: \`${run.url}\`

| | Status | Duration |
|---|---|---|
${rows}
${truncated}${dashLink}

_Generated by [@hasna/testers](https://www.npmjs.com/package/@hasna/testers)_`;
}

export async function postGitHubComment(
  run: Run,
  results: Result[],
  options?: { prNumber?: number; dashboardUrl?: string },
): Promise<boolean> {
  const token = process.env["GITHUB_TOKEN"];
  if (!token) return false;

  // Detect PR number: explicit option > GITHUB_PR_NUMBER env > parse from GITHUB_REF
  let prNumber = options?.prNumber;
  if (!prNumber && process.env["GITHUB_PR_NUMBER"]) {
    prNumber = parseInt(process.env["GITHUB_PR_NUMBER"]!, 10);
  }
  if (!prNumber) {
    // GITHUB_REF format: refs/pull/123/merge
    const ref = process.env["GITHUB_REF"] ?? "";
    const match = ref.match(/refs\/pull\/(\d+)\//);
    if (match) prNumber = parseInt(match[1]!, 10);
  }
  if (!prNumber) return false;

  // Detect repo from GITHUB_REPOSITORY (owner/repo)
  const repo = process.env["GITHUB_REPOSITORY"];
  if (!repo) return false;

  const body = formatPRComment(run, results, options?.dashboardUrl ?? process.env["TESTERS_DASHBOARD_URL"]);
  const apiUrl = `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`;

  try {
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({ body }),
    });
    return response.ok;
  } catch {
    return false;
  }
}
