/**
 * Format and post structured PR comments with test results.
 * Generates markdown suitable for GitHub PR comments.
 */

import type { Run, Result } from "../types/index.js";

export interface PRCommentOptions {
  run: Run;
  results: Result[];
  /** Link to the full report (optional) */
  reportUrl?: string;
  /** Link to the PR (optional) */
  prUrl?: string;
  /** Number of retries for this run */
  retries?: number;
  /** Total cost of the run */
  costCents?: number;
}

/**
 * Generate a structured markdown comment for a PR with test results.
 */
export function formatPRComment(options: PRCommentOptions): string {
  const { run, results, reportUrl, prUrl, retries, costCents } = options;

  const passed = results.filter((r) => r.status === "passed").length;
  const failed = results.filter((r) => r.status === "failed").length;
  const errors = results.filter((r) => r.status === "error").length;
  const skipped = results.filter((r) => r.status === "skipped").length;
  const total = results.length;

  const overallStatus = failed > 0 || errors > 0 ? "FAILED" : "PASSED";
  const statusEmoji = overallStatus === "PASSED" ? "\u2705" : "\u274C";

  const lines: string[] = [];

  // Header
  lines.push(`## ${statusEmoji} Test Results: ${overallStatus}`);
  lines.push("");

  // Summary
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Total Scenarios | ${total} |`);
  lines.push(`| Passed | ${passed} |`);
  if (failed > 0) lines.push(`| Failed | ${failed} |`);
  if (errors > 0) lines.push(`| Errors | ${errors} |`);
  if (skipped > 0) lines.push(`| Skipped | ${skipped} |`);
  lines.push(`| Duration | ${formatDurationMs(run)} |`);
  lines.push(`| Model | \`${run.model}\` |`);
  if (costCents != null) lines.push(`| Cost | ${formatCostCents(costCents)} |`);
  if (retries != null && retries > 0) lines.push(`| Retries | ${retries} |`);
  lines.push("");

  // Failed scenarios (if any)
  if (failed > 0 || errors > 0) {
    lines.push("### Failed Scenarios");
    lines.push("");

    for (const r of results) {
      if (r.status === "failed" || r.status === "error") {
        const scenarioId = r.scenarioId.slice(0, 8);
        lines.push(`- **\`${scenarioId}\`** [${r.status.toUpperCase()}] ${r.reasoning ?? r.error ?? "No details"}`);
      }
    }
    lines.push("");
  }

  // All results summary
  if (results.length <= 20) {
    lines.push("### All Results");
    lines.push("");
    lines.push("| Status | Scenario ID | Model | Duration | Tokens |");
    lines.push("|--------|------------|-------|----------|--------|");
    for (const r of results) {
      const icon = r.status === "passed" ? "\u2705" : r.status === "failed" ? "\u274C" : r.status === "error" ? "\u26A0\uFE0F" : "\u23ED\uFE0F";
      lines.push(
        `| ${icon} ${r.status} | \`${r.scenarioId.slice(0, 8)}\` | ${r.model} | ${formatMs(r.durationMs)} | ${r.tokensUsed.toLocaleString()} |`,
      );
    }
    lines.push("");
  }

  // Links
  const linkLines: string[] = [];
  if (reportUrl) linkLines.push(`[Full Report](${reportUrl})`);
  if (prUrl) linkLines.push(`[Pull Request](${prUrl})`);
  if (linkLines.length > 0) {
    lines.push(linkLines.join(" | "));
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by [open-testers](https://github.com/hasna/open-testers)_");

  return lines.join("\n");
}

function formatDurationMs(run: Run): string {
  if (run.startedAt && run.finishedAt) {
    const ms = new Date(run.finishedAt).getTime() - new Date(run.startedAt).getTime();
    return formatMs(ms);
  }
  return "N/A";
}

function formatMs(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  const mins = Math.floor(ms / 60000);
  const secs = Math.round((ms % 60000) / 1000);
  return `${mins}m ${secs}s`;
}

function formatCostCents(cents: number): string {
  if (cents < 1) return `$${(cents / 100).toFixed(4)}`;
  return `$${(cents / 100).toFixed(2)}`;
}

/**
 * Generate a compact check summary for GitHub commit status.
 * Returns a simple pass/fail line suitable for check runs.
 */
export function formatCommitStatus(run: Run, results: Result[]): string {
  const passed = results.filter((r) => r.status === "passed").length;
  const failed = results.filter((r) => r.status === "failed").length;
  const errors = results.filter((r) => r.status === "error").length;
  const total = results.length;

  const status = failed > 0 || errors > 0 ? "failure" : "success";

  return `open-testers/${run.model} — ${status} (${passed}/${total} passed, ${failed} failed, ${errors} errors)`;
}
